### ISSUE TITLE
Doesn't appear to deal with nested attributes

### ISSUE THREAD

**Issue by jph** [readysteady/formeze#6]
I'm trying out Formeze right now, and I've already thought of lots of applications for it. Rails really misses out on first-class forms, and this is absolutely the closest thing I've come across that does the job.

I'm running into an issue (not sure if it's me or not): When an attribute name is something like `user[email_address]`, I can't seem to find a way to define this correctly in a Formeze::Form interface. Am I missing something, or is there no support for attributed named in this way at this time? Please let me know.

**Comment by timcraft** [comment]
@jph Nested parameters are a Rails feature and Formeze isn't tied to Rails, so you have to do things slightly differently to how you'd use params in Rails. Depends on your form but the obvious field name would be "email_address". If you need to disambiguate you can prefix (e.g. "user_email_address") or suffix (e.g. "email_address_1"). Hope that helps.
